apiVersion: v1
kind: ServiceAccount
metadata:
  name: btg-funds-sa
  namespace: ceiba-test
  annotations:
    # IRSA: usar un rol IAM dedicado para pods con trust policy OIDC del cluster.
    # No usar el rol de nodos EKS aqui. Reemplaza con tu rol IRSA real.
    eks.amazonaws.com/role-arn: "arn:aws:iam::<ACCOUNT_ID>:role/<IRSA_ROLE_NAME>"
  labels:
    app: btg-funds-api

